version: '3.9'
services:
  # Uncomment to run the emergency generators example
  # generators:
  #   image: emergency-generator:latest
  #   depends_on:
  #     mosquitto:
  #       condition: service_healthy
  #   environment:
  #     - GENERATORS=3
  #     - BROKER=mosquitto
  #   networks:
  #     - mqtt
  
  # Uncomment to run the construction example 
  construction:
    image: construction-site:latest
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - VEHICLE=1
      - BROKER=mosquitto
    networks:
      - mqtt
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      mosquitto:
        condition: service_healthy
    networks:
      - mqtt
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "hello"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - mqtt
    volumes: 
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  # Option to use InfluxDB v2 OSS 
  # influxdb:
  #   image: influxdb:latest
  #   volumes:
  #     # Mount for influxdb data directory and configuration
  #     - ./influxdb/data:/var/lib/influxdb2:rw
  #   ports:
  #     - 8086:8086

    # networks:
    #   - mqtt
networks: 
  mqtt:
    name: mqtt